services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - "../:/var/www"
  php:
    build: ./php
    volumes:
      - "../:/var/www"

  db:
    image: "postgres:15.2-alpine"
    restart: always
    ports:
      - 54321:5432
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    